name: CD

on:  
  push:
    branches: [ main ]

jobs:
  build_and_release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Echo
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: echo-example
    - name: Build
      run: dotnet build --no-restore
      working-directory: echo-example
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: echo-example
    # Service 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: service-example
    - name: Build
      run: dotnet build --no-restore
      working-directory: service-example
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: service-example
    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        generate_release_notes: true
        files: |
          echo-example/bin/**/*
          service-example/bin/**/*
